### ISSUE TITLE
The Local

### ISSUE THREAD

**Issue by ryanatk** [ryanatk/junction#10]
1. review the new homepage
    - https://thelocal-cville.squarespace.com/homepage-uva-graduation
    - new layout, new links
1. food menu is updated
    - https://thelocal-cville.squarespace.com/food/
    - review for any changes
1. drink menu is updated
    - https://thelocal-cville.squarespace.com/drink/
    - do we want to add any more drinks?
    - do we have a pdf to link to for wine, etc?
1. photos
    - https://thelocal-cville.squarespace.com/photos/
    - is there a collection of photos i can upload?
1. updated the form on private events
    - https://thelocal-cville.squarespace.com/private-events/
    - i will update the "Our Rooms" section once i get the content
1. about us
    - https://thelocal-cville.squarespace.com/about-us/
    - i cannot recall what we decided (cannot find notes)
1. contact us is updated
    - https://thelocal-cville.squarespace.com/contact-us/
    - what email address should each form submit to? also google docs?
1. uva grad weekend page is created
    - https://thelocal-cville.squarespace.com/uva-graduation-weekend
    - links on homepage and contact-us
1. added facebook link to footer
1. need url for catering site

as we finish these remaining details, it would be great to start work on the catering site, this week

**Comment by ryanatk** [comment]
i've taken a few stabs at the homepage changes. these shapes & sizes can be combined differently.

red outlined buttons
![image](https://cloud.githubusercontent.com/assets/156617/22907450/103a7f76-f1fe-11e6-82cc-b355ad3e47d7.png)

grey buttons with red text
![image](https://cloud.githubusercontent.com/assets/156617/22907518/63e8e018-f1fe-11e6-945f-a71108b3a057.png)

red "pill" buttons
![image](https://cloud.githubusercontent.com/assets/156617/22907639/e924ca30-f1fe-11e6-9197-dbbc4a29dd55.png)

**Comment by ryanatk** [comment]
i've also performed the following updates:

- removed "drinks" from the "food" menu
- added a link/button to the bottom of the "drinks" menu page that links to the "wine + beer" menu (pdf). this looks like the best way to manage that pdf, as editing the link itself lets you easily upload a new pdf anytime, and it automatically updates the link for you.
- updated the email address for all forms, and added google docs for each, and shared with thelocalcalendar@gmail.com
- added "additional info/disclaimer" text below "submit" button on grad weekend form
- updated all links to "catering site" to //catering.thelocal-cville.com

i will update the following pages once i get images/content: photos, about-us, private-events

**Comment by mishmosh525** [comment]
I like the middle one (grey buttons). Any way we can make them the same
width?

Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>

**Comment by ryanatk** [comment]
i've updated the homepage "buttons" to the gray style, with equal widths
https://thelocal-cville.squarespace.com/

**Comment by ryanatk** [comment]
i've updated the private events page with the new images and text
https://thelocal-cville.squarespace.com/private-events/

**Comment by ryanatk** [comment]
Remaining assets needed to complete The Local site:

**updated "wine + beer" menu (pdf)**
https://thelocal-cville.squarespace.com/drink/

**photos of food and the restaurant**
https://thelocal-cville.squarespace.com/photos/

**content for "about us"**
https://thelocal-cville.squarespace.com/about-us/

Once we have these, I will update the site. And we can discuss the catering site once you're ready.
