### ISSUE TITLE
Catering Website

### ISSUE THREAD

**Issue by ryanatk** [ryanatk/junction#11]
# Initial Questions

1. **Will we use the same template/layout/style as The Local & Junction?**
yes

1.  **What is the color scheme?**
light blue "wedding" color. ryan will just pick one now (#a6d4eb)
    - [ ] michelle to send a proper color later

1. **Do we have a logo?**
    - [ ] michelle to send the logo later

# Pages

## Catering

1. **Should this be the homepage? If not, can we call the page "Contact Us" in the header navigation?**
yes, this will appear on the homepage

## Taste of Virginia

1. **It looks like the main point of this page is to include 2 links, opening PDF's for the "Catering Event Menu" and the "Bar Packages"**
this will be its own simple page

1. **This is a long title for the header navigation. Is there something shorter we can use?**
we'll try the long title first

## About Us

1. **Do you have the actual photos for "Our Team"? (If not, I can grab them from the PDF, but they may not be the best quality)**
    - [ ] michelle is sending team member photos

## Wedding Services

1. **This one seems straightforward, adding all links from the PDF into the page.**
this will be a long page, including all the links from the pdf, separated into sections. each section should include its own header and image (implement a clever design, so the page doesn't go on forever)
    - [ ] michelle will provide these images

## Accolades & Features

1. **Can we use the same layout & style from The Local's "Press" section on the "About Us" page? It includes thumbnails, links to the article, and includes an excerpt.**
👍 

1. **Do we want to include the additional customer testimonials? If so, do we also want the handwritten testimonials?**
yes, include the 3 typed testimonials. we'd like to include the handwritten, but we're not sure how to do that well, so we'll hold off for now.

1. **Can we include this as a section in the "About Us" page? If not, can we call this page "Press" in the header navigation?**
yup

## Image Gallery

1. **There are over 100 images. How should we group/arrange them? Similar to The Local, with "Food" & "Restaurant" sections on 1 "Photos" page. Alternatively we can break them into sections with sliders, like the "Private Events" page.**
ryan is trying to break these up into sections: "food & drink", and 1 for each venue, and a miscellaneous that we'll figure out later. because there are so many images, ryan is trying to use "tags" for these. this might make ryan go crazy, and start speaking in 3rd person. ryan will see how it goes.

1. **Can we call this page "Photos" in the header navigation?**
yup

# Additional Questions

1. **What will our homepage look like?**
similar to the local's homepage, but will not include "open table" (replace with links to the form & menus), and replace buttons with catering info (header & text).

1. **To what email address should the "Catering Inquiry" form submit?**
catering@thelocal-cville.com

1. **Does the catering team have a "Daniel" or "Will" that will be the main person for future updates?**
this will come later

**Comment by ryanatk** [comment]
https://thelocalcatering.squarespace.com/

### Outstanding Questions

- [ ] header, logo, and color scheme?
- [ ] footer link to "join our team"?
- [ ] homepage: header text
- [ ] homepage: form button - can we just link to the form page instead of opening in a lightbox?
- [ ] about us: links for the B&B awards?
- [ ] anything i missed?

**Comment by mishmosh525** [comment]
- Logo seems a little off (even though I suggested that!). I'd say we
either drop it down completely so the top isn't cut off, or create a solid
square background around the logo so that there is no white behind it?
- Color scheme: we all like it, but realize one of out competitors use it!
We want to go with a slate blue. If you can match RGB: red 141 / green 170
/ blue 197?
- Header looks great otherwise!
- Join Our Team: Change to "Careers" and we can create a new lightbox form
that has the same fields as our application (attached). If that is too much
to have on an online form I can cut out some stuff
- homepage form button - yes no need for lightbox. Can we make the button
the same width as the image?
- B&B:
https://www.borrowedandblue.com/charlottesville/wedding-catering/the-local
or https://www.borrowedandblue.com/charlottesville/best-of-bnb/vendors/2017.
The second one lists all the winners and we are the very bottom, so I'm
inclined to just link straight to our page (the first link)


Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 <(434)%20465-6130> (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>

**Comment by ryanatk** [comment]
oh no! i liked the logo! i dropped it down so the top is not cut off, to see what you think. i still dig it.
![image](https://user-images.githubusercontent.com/156617/28431143-0caf1c9e-6d38-11e7-83ce-e4bfe8d1f2f1.png)

and i tried adding some white space above the header, making the header look more like a "stripe", which i think is cool
![image](https://user-images.githubusercontent.com/156617/28431179-43a25c70-6d38-11e7-98b7-5c9cb9fa0a8d.png)

i also tried shrinking the logo just a bit, but when it only overlaps a tiny bit, it looks like the website is broken.

does one of those work better for you?

everything else on your list looks good, except i cannot find the "career application" attachment. would you mind emailing that straight to me? ryan@ratkinson.com

if it's a lot to fill out, we're likely better not using the "lightbox" form, and just linking to a page (like the "request a quote" link does). lightboxes can get janky when the user needs to scroll within it.

**Comment by mishmosh525** [comment]
Let's go with the centered one, but increase the logo size slightly so that
the inner circle is the same height as the bar. I think we are good then!
Can you hook me up with admin info so I can do some text editing?

Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>

**Comment by mishmosh525** [comment]
Also, could we just make the top bar "thicker"?

Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>

**Comment by ryanatk** [comment]
if we make the top bar thicker AND we want the logo's inner circle to cover the whole top bar, the logo will be HUGE. how about we go with option #1 above, where we just dropped the logo down (so the top is not cut off) ?

**Comment by ryanatk** [comment]
also, i sent you an invite to be an "admin". when you have a chance, would you mind adding your payment info for the monthly billing? https://thelocalcatering.squarespace.com/config/settings/billing/billing

**Comment by mishmosh525** [comment]
Yup, fine as is!

Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>

**Comment by ryanatk** [comment]
ok, all feedback above has been addressed. the last piece i have left is building the job application, and i plan to get that done tomorrow.

for the awards, i used both B&B links, and i reordered them. i think that 2nd link is a good one, but we can change it if you prefer.

and if you see any other changes you'd like, please let me know. we went thru this site much faster than the first two, and i know it might need to soak in a bit to see how the team feels.

also, while you're updating text, please feel free to move things around. that "Cancel" button at the top is our best friend, and there isn't much you can break that cannot be fixed again. better to get comfortable with the system now, while i'm still actively involved 👍

**Comment by ryanatk** [comment]
oh, 1 more thing: we need the text for the homepage "headline"

**Comment by mishmosh525** [comment]
Done! How to we go about getting this live? I think we are in good shape to
do that, even though there are a fair amount of small edits.

Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>

**Comment by ryanatk** [comment]
are we going with catering.thelocal-cville.com ?

if so, i can set up the DNS now, and it should propagate before tomorrow. then, after i build the application, i can start pointing the catering links on the main site to this new site. sound good?

**Comment by mishmosh525** [comment]
perfect!

Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>

**Comment by mishmosh525** [comment]
After all that, the catering kids hate the logo dropping below the blue
haha. Option 1 is that the line that splits the logo in half lines up with
the bottom of the blue band. Option 2 is just shrink it down to fit the
band. sorry! so many opinions over here

Michelle Moshier
Director of Operations

*Hawthorne Hospitality*
434.465.6130 (direct)
michelle@hawthornehospitality.com
824 Hinton Ave
Charlottesville, VA 22902

Partner Restaurants:

<http://www.thelocal-cville.com/>     <http://www.junctionva.com/>
<http://www.thelocalsmokehouse.com/>
