### ISSUE TITLE
re-add opentable widget

### ISSUE THREAD

**Issue by ryanatk** [ryanatk/junction#7]
we had to remove the opentable widget from the homepage, because junction is not setup on opentable yet. we will re-add that once it's ready.
https://junctionva.squarespace.com/config/pages

**Comment by RiceBarrel** [comment]
Emailed instructions from OpenTable representative on suggested setup for widget.

**Comment by ryanatk** [comment]
Hello Michelle,

As a new OpenTable client, Junction will soon be able to offer real-time restaurant reservations from its own website. We need your help (1) adding online reservations to the restaurant's website and (2) activating the mobile website (if applicable). Could you forward the below instructions to your webmaster to setup?



(1) Add Online Reservations to the Restaurant's Website 
Below is the code you need to add to the restaurant's website and an example of what you can add to the restaurant's website. Click here for more color and/or display options.


<script type="text/javascript" src="http://www.opentable.com/frontdoor/default.aspx?rid=347287&restref=347287&hover=1"></script>
<a class="OT_ExtLink" href="http://www.opentable.com/single.aspx?rid=347287&restref=347287">Junction</a>

The Restaurant ID (RID) for your restaurant is 347287.

 

In addition to the booking widget/ button, you can add a basic reservation link to the site.

Junction reservation link: http://www.opentable.com/single.aspx?rid=347287&restref=347287
(2) Claim the restaurant's FREE mobile website 
In the restaurant's website index.html file, paste the code below into the ‹head› tag. If you would like to edit the mobile website, please reply to this email and we will get you access to do so.

 

Need help? email reservationlinks@opentable.com



Sincerely, 


Thomas

**Comment by RiceBarrel** [comment]
And he recommended the in-site functionality for making a reservation, vs taking the guest to the opentable site.

**Comment by ryanatk** [comment]
it looks like this is not yet ready on the opentable end
http://www.opentable.com/single.aspx?rid=347287&restref=347287
