### ISSUE TITLE
Confirmation emails for Contact Us forms sent to client.

### ISSUE THREAD

**Issue by RiceBarrel** [ryanatk/junction#8]
"We have received your information and a member of our team will contact you shortly. If you do not hear from us within two business days, feel free to contact us at (434) 465-6131. Thank you."

**Comment by ryanatk** [comment]
are you asking for automatic replies when somebody submits a contact form?
https://answers.squarespace.com/questions/20454/how-can-i-send-a-confirmation-email-after-a-form-is-submitted.html#answer-26812

**Comment by RiceBarrel** [comment]
Yeah, same reply works for all forms. If possible.

**Comment by ryanatk** [comment]
i've found 3 potential options:

1. for $10 a month, mailchimp can automate this for you. if you plan to start marketing to folks directly, mailchimp is fantastic. if you don't plan to market, it seems like overkill.
1. use a combination of 
    - a google docs script (to watch the spreadsheet) to send an email to junctionva using a gmail
    - the junctionva email server send a new email to the customer, using the email address sent from gmail. this is the part you'll have to set up.
1. stick with the pop up messaging on the site, with no confirmation email

let me know what you think?
